{"name": "test_03", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <TestCases.test_demo.TestA object at 0x000001FCA60AFE20>\n\n    @pytest.mark.demo\n    def test_03(self):\n        print('this is c test')\n>       assert False\nE       assert False\n\nTestCases\\test_demo.py:20: AssertionError"}, "start": 1651132934999, "stop": 1651132934999, "uuid": "3780daf5-f345-4cb4-ba58-78b0f9ac0e8c", "historyId": "f0751cb4fab82d500484bd9b5df5b3dc", "testCaseId": "896f4bcaf965afd9024bd6b9b2162fa0", "fullName": "TestCases.test_demo.TestA#test_03", "labels": [{"name": "tag", "value": "demo"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_demo"}, {"name": "subSuite", "value": "TestA"}, {"name": "host", "value": "gfl2171"}, {"name": "thread", "value": "62072-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_demo"}]}